config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :logins

  scope "/admin" do
    resources :users
  end

  get 'two_factors/new', as: "two_factors_new"
  post 'two_factors/create', as: "two_factors_create"

  get '/logins', to: "logins#index"

  post 'users/enable_otp'
  post 'users/allow_tfa'

  post 'users/verify_enabled'
  post 'users/verify_disabled'

  post 'users/disable_otp'
  post 'users/deny_tfa'
  root to: "users#index"
  
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::OneTimePassword
  # devise :registerable, :trackable,
  #       :recoverable, :rememberable, :validatable, :two_factor_authenticatable,
  #       authentication_keys: [:login], :otp_secret_encryption_key => ENV['test_key']

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  define_model_callbacks :create
  # attr_accessor :otp_secret_key, :email

  has_many :logins, dependent: :destroy
       
  has_one_time_password
  enum otp_module: { disabled: 0, enabled: 1 }, _prefix: true
  attr_accessor :otp_code_token

  # dili case sensitive ang username
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  # para dili maka fill up ug email sa 'Username' na field
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  attr_writer :login
  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      Rails.logger.info "here in if"
      where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      Rails.logger.info "here in else"
      where(conditions.to_h).first
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   # User = warden.authenticate!(auth_options)
  #   # set_flash_message!(:notice, :signed_in)
  #   # sign_in(resource_name, user)
  #   # yield user if block_given?
  #   # respond_with user, location: after_sign_in_path_for(user)
  #   # super && signed_in?
  #   # redirect_to(users_path) and return
  #   # sign_out(@user)
  #   # Rails.logger.info "session: #{session}"
  # end

    
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  # def auth_options
  #   { scope: resource_name, recall: "#{controller_path}#new" }
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def create
    self.resource = warden.authenticate!(auth_options)
    if resource && resource.admin_allow_tfa?
      continue_to_otp(resource, resource_name)
    elsif #resource && resource.admin_allow_tfa?
      continue_sign_in(resource, resource_name)
    end
  end

  private
    def continue_sign_in(resource, resource_name)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      resource.logins.create!(ip_address: request.remote_ip, user_agent: request.user_agent, last_sign_in: resource.current_sign_in_at, username: resource.username, email: resource.email)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    end

    def continue_to_otp(resource, resource_name)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: two_factors_new_path(params.to_unsafe_h)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def verify_enabled user_id=params[:user_id] || current_user.id
    user=User.find user_id
    user.otp_module_enabled!
    user.save!
    redirect_to users_path
  end

  def verify_disabled user_id=params[:user_id] || current_user.id
    user=User.find user_id
    user.otp_module_disabled!
    user.save!
    redirect_to users_path
  end 

  def logins
    @user = User.find(params[:user_id])
    @login = @user.logins.find(params[:id])
  end

  def index
    @users = User.all
    if Rails.env.production?
      @country = request.location.country
      @city = request.location.city
      @coordinates = request.location.coordinates
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def create
    Rails.logger.info('I AM IN USERS CREATE')
    @user = User.new(user_params)

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.save!
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end
end

app/views/users/_form.html.erb
<div class="container">
    <div class="col-md-6">
      <%= form_for @user do |form| %>
        <div class="form-group"></div>
          <%= label_tag :username %>
          <%= form.text_field :username, autofocus: true, class: "form-control" %>

        <div class="form-group"></div>
          <%= label_tag :email %>
          <%= form.email_field :email, autocomplete: "email", class: "form-control" %>
        
        <div class="form-group"></div>
        <%= label_tag 'Password (must be at least 6 characters)' %>
        <%= form.text_field :password, class: "form-control" %>
        
        <div class="form-group"></div>
          <%if current_user.admin?%>
              <%= label_tag :admin %>? Check if yes
            <%= form.check_box :admin %>
          <% end %>
        <%= form.submit "Submit", class: "btn btn-primary float-right" %>
      <% end %>
    </div>
</div>

app/views/users/_index.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Username</th>
          <th scope="col">Email</th>
          <th scope="col">Current IP</th>
          <th scope="col">Last IP</th>
          <th scope="col">Admin</th>
          <th scope="col">User Agent</th>
          <th scope="col">Coordinates</th>
          <th scope="col">Country</th>
          <th scope="col">City</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.order(:username).each do |user| %>  
        <tr>
          <th scope="row"><%= user.username%></th>
          <td><%= user.email %></td>
          <td><%= user.current_sign_in_ip %></td>
          <td><%= user.last_sign_in_ip %></td>
          <td><% if user.admin? %>
                Yes 
              <% elsif %>
                No 
              <%end%>
          </td>
          <td><%= request.user_agent %></td>
          <td><%= @coordinates %></td>
          <td><%= @country %></td>
          <td><%= @city %></td>
          <td>
            <div>
            <%= link_to "EDIT", edit_user_path(id: user.id) %> /
            <%= link_to "DELETE", user_path(id: user.id), method: :delete, 
              data: { confirm: "Are you sure you want to delete user: #{user.username} ?"  } %>
            <% if user %>
              <% if user.otp_module_enabled? %>
                <%= button_to "Disable 2FA", users_verify_disabled_path(user_id: user.id), :method => :post, class: "btn btn-primary"  %><br />
              <% end %>

              <% if user.otp_module_disabled? %>
                <%= button_to " Enable 2FA ", users_verify_enabled_path(user_id: user.id), :method => :post, class: "btn btn-primary"%><br />
              <% end %>

            <% end %>
            </div>
          </td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_show.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Username</th>
          <th scope="col">Email</th>
          <th scope="col">Current IP</th>
          <th scope="col">Last IP</th>
          <th scope="col">Admin</th>
          <th scope="col">User Agent</th>
          <th scope="col">Coordinates</th>
          <th scope="col">Country</th>
          <th scope="col">City</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"><%= @user.username%></th>
          <td><%= @user.email %></td>
          <td><%= @user.current_sign_in_ip %></td>
          <td><%= @user.last_sign_in_ip %></td>
          <td><% if @user.admin? %>
                Yes 
              <% elsif %>
                No 
              <%end%>
          </td>
          <td><%= request.user_agent %></td>
          <td><%= @coordinates %></td>
          <td><%= @country %></td>
          <td><%= @city %></td>
          <td>
            <div>
            <%= link_to "EDIT", edit_user_path(id: @user.id) %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/users/after_login.html.erb
This is new! This is what admin_tfa_allow = true looks like.
<br />
<br />
<br />
<%= params %>
<br />
<br />

app/views/users/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="col-md-12">
    <%if current_user.admin?%>
      <bebas><h2>Admin's Dashboard</h2></bebas>
      <%= link_to "Create New User", new_user_path() %>
      <div class="users-index">
        <div class="row">
          <div class="col-md-12">
            <%= render 'index' %>
          </div>
        </div>
      </div>
      <% else %>
      <div>
        <bebas><h2>User Dashboard</h2></bebas>
      </div>
      <% @user = current_user %>
      <%= button_to "View Login History", logins_path(user_id: @user.id), :method => :get %> <br />
      <%= render 'show'%>
    <%end%>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-md-12">
    
    <div>user: <%= @user.username%></div>
    <div>email: <%= @user.email %></div>
    <div>current signin ip: <%= @user.current_sign_in_ip %></div>
    <div>last signin ip: <%= @user.last_sign_in_ip %></div>
      <div>Admin? 
      <% if @user.admin? %>
        Yes
      <% elsif %>
        No
      <%end%>
    </div>

    <div>User agent: <%= request.user_agent %></div>
    
    <div>
      User country: <%= @country %><br />
      User city: <%= @city %><br />
      User coordinates: <%= @coordinates %><br />
    </div>

    <div>
      <%= link_to "edit user", edit_user_path(id: @user.id) %> 
      |
      <%= link_to "delete user", user_path(id: @user.id), method: :delete,
        data: { confirm: "Are you sure you want to delete user: #{@user.username} ?"  } %> <br /><br />
    </div>
  </div>
</div>