config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :logins

  scope "/admin" do
    resources :users
  end

  get 'two_factors/new', as: "two_factors_new"
  post 'two_factors/create', as: "two_factors_create"

  get '/logins', to: "logins#index"

  post 'users/enable_otp'
  post 'users/allow_tfa'

  post 'users/verify_enabled'
  post 'users/verify_disabled'

  post 'users/disable_otp'
  post 'users/deny_tfa'
  root to: "users#index"
  
end

app/controllers/two_factors_controller.rb
class TwoFactorsController < ApplicationController
  def new
    @save_current_user = current_user.dup

    if current_user.otp_module_enabled?
      Rails.logger.info('THIS OTP MODULE IS ENABLED')
      Rails.logger.info('THIS OTP MODULE IS ENABLED')
      Rails.logger.info('THIS OTP MODULE IS ENABLED')
      Rails.logger.info('THIS OTP MODULE IS ENABLED')
    else
      session[:otp_code] = '123'
      redirect_to users_path
    end
  end

  def create
    if current_user.authenticate_otp(params[:otp_code_token], drift: 60)
      current_user.otp_module_enabled!
      session[:otp_code] = params[:otp_code_token]
      redirect_to users_path, notice: 'Two Factor Authentication Enabled'
    else
      redirect_to two_factors_new_path, alert: 'Two Factor Authentication could not be enabled'
    end
  end


end

app/views/two_factors/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
      <div class="col-md-4 col-md-4 border-top border-bottom border-left border-right pt-5 pb-5 pl-5 pr-5 text-left", id="rcorners2">
        <%
        require 'active_model_otp'
          # qrcontent=@save_current_user.provisioning_uri(@save_current_user.email, issuer: "Project Tu-FA")
          qrcontent = @save_current_user.provisioning_uri(nil, issuer: 'Project Tu-FA')

          qrcode = RQRCode::QRCode.new(qrcontent)
          qrsize = 250

          svg = qrcode.as_svg(
            offset: 0,
          color: '000',
          shape_rendering: 'crispEdges',
          module_size: 6,
          standalone: true
          )

          image64_svg = Base64.encode64(svg)
          image_source_svg="data:image/svg+xml;charset=utf-8;base64,#{image64_svg}"
        %>
        <div class="pb-4"> 
          <img src="<%= image_source_svg %>" width="<%= qrsize %>" height="<%= qrsize %>" alt="WhatEver" style="display: block; margin: 0 auto;">
        </div>
        
        <div class="text-center"> 
          <%= form_tag(two_factors_create_path) do %>
          <%= text_field_tag :otp_code_token, nil, id:"login", placeholder: 'Enter 6-digit OTP here' %>
          <%= submit_tag "Signin", class:'btn btn-primary btn-block' %>
          <% end %>
        </div>
      </div>
    <div class="col-md-4"></div>
  </div>
</div>